### ISSUE TITLE
Thank you very much

### ISSUE THREAD

**Issue by percybolmer** [ymgn-dev/testing_svelte_mdsvex#1]
This helps me fix the same issue that I have.
I would never find that prose stuff without you. 

Thank you very much! 

Now, prose does seem to overwrite my themes primary-text settings, any idea how to overcome that?

**Comment by percybolmer** [comment]
Edit: I found that using jit mode and adding ! infront of themeing classes will cause an !important to be added. Closing issue.

**Comment by ymgn-dev** [comment]
Thank you too! Have a great holiday!
